commit-msg hook made interactive

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -8,11 +8,16 @@ if [ "$?" != "0" ]; then
     echo "Save a story ID in the '.pivotal' dotfile in project root directory"
     echo "or specify it in \$STORY environment variable."
     echo
-    echo "If it's fine, that no story should be assigned to this particular"
-    echo "commit, re-run commit command with '--no-verify' switch. But you"
-    echo "must be aware that this approach will skip all other validations."
+    echo "If you know what you're doing, but you know, for real... Then you can"
+    echo "force this operation now."
     echo
-    echo "Aborting..."
 
-    exit 1
+    exec < /dev/tty
+    read -p "Do you want to commit anyway? (y/N) " answer
+
+    if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
+        echo
+        echo "Aborting..."
+        exit 1
+    fi
 fi
