pre-commit master checking made interactive

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -5,12 +5,16 @@ if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ]; then
     echo "on some issues or new features then you should get it done in a separate"
     echo "branch and merge changes to master after you finish."
     echo
-    echo "If you know what you're doing, but you know, for real... then you can"
-    echo "force this operation by re-running commit command with '--no-verify'"
-    echo "switch. But you must be aware that this approach will skip all further"
-    echo "checkings, i.a. commit message format validation."
+    echo "If you know what you're doing, but you know, for real... Then you can"
+    echo "force this operation now."
     echo
-    echo "Aborting..."
+    
+    exec < /dev/tty
+    read -p "Do you want to commit anyway? (y/N) " answer
 
-    exit 1
+    if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
+        echo
+        echo "Aborting..."
+        exit 1
+    fi
 fi
